### ISSUE TITLE
Milestone 1 feedback

### ISSUE THREAD

**Issue by aditi48n** [UBC-MDS/cervical-cancer-predictor#15]
Congratulations on finishing milestone 1! We can see you put a lot of work into this project, nice work! Below we list some specific feedback you can use to improve your project. We provide tick boxes for you to use in the future as you address these concerns to improve the final grade of your project. If anything is unclear, please feel free to ask questions in this issue thread.

Code of Conduct.md
- [x] A list of consequences for unacceptable behaviour -1
**Comment:** Not mentioned within the document. 
- [x] A Statement on diversity and inclusivity -1
**Comment:** Not mentioned within the document. 

CONTRIBUTING.md
- [x] Contributing documentation should reflect all the ways people can contribute to the project (core members, who should be working in a GitHub flow workflow involving branching in the main project repo and opening PR's, as well as arms-length contributors, who more likely may have to fork the repo before submitting a PR). -1
**Comment:** Core teams contribution workflow is not mentioned

A script that downloads and saves the data
- [x]  The script is placed in an appropiated subdirectory as the src folder -1
**Comment:** Not placed within the src folder. 

Exploratory data analysis in a literate code document
- [x] There are not figure captions. -2 viz
**Comment:** Figure captions are missing
- [x]  Dependencies (or link pointing to list elsewhere) is missing from the README.md file. The dependency list should include docopt package. -2
**Comment:** No dependencies listed in the readme

**Comment by samson-bakos** [comment]
Hi Aditi, quick question. 

Regarding EDA, we were taught in our previous courses (531, 571 and 573, etc) that in initial EDA we usually don't need figure captions as EDA not in the final analysis is purely for our usage and speed/efficiency is valued, and it is assumed we can understand our own EDA without captions. I see that it does say captions in the milestone description (I think we just missed this), and obviously we will include captions in the EDA of our final report packaged for readers, but I do want to observe that our previous learning we were told we don't need to do this for very initial work, and having this requirement in the Milestone 1 was a little surprising

**Comment by samson-bakos** [comment]
Also, regarding addressing concerns on the teamwork contract; because this is a private document that does not live in our repo, how should we provide evidence of our updating it?

**Comment by samson-bakos** [comment]
Also, regarding the contributing file, there was no mention of the specific need to add our workflow to the document in either the milestone instructions or the example template provided, so we had know way of knowing that this was expected. We discussed our workflow in detail and all agreed, and since the instructions did not call on us to document this, we assumed our discussion was sufficient.

**Comment by aditi48n** [comment]
Hello Samson, 

I do understand the points you have raised. I have graded groups based on a rubric set by Florencia. With respect to the first issue where you talked about the captions, I unfortunately cannot do much since requirement for captions was mentioned in Milestone 1 instructions. I understand that this is not what you were taught before and went with your prior knowledge. 
My understanding is that the team work contract is for you all as a team to abide by and update. I am not certain if I would need to check that every week. I am not sure about this and will bring this up with Florencia and get back to you.
I do realise from the instructions that core team contributions wasnt specified and will bring that to Florencia's attention. Thank you for pointing it out. I will have a chat with her and update your marks accordingly.

**Comment by samson-bakos** [comment]
Hi Aditi, thank you so much for your quick and considerate response.

 I may ask Florencia about the captions rubric myself in that case, since I spoke to multiple other groups who also made the same mistake based on our prior knowledge.

Please do let us know when you find out the best way to update our contract!

**Comment by aditi48n** [comment]
Hi Samson, 
Ofcourse. I’m happy to help in whatever way I can. I have also sent Florencia a link to this issue so she will have the context when you speak with her so I believe that should help you out as well. I’ll let you know as soon as I hear from her. Good luck on Milestone 2.
