### ISSUE TITLE
Milestone 2 Feedback

### ISSUE THREAD

**Issue by muntakimrafi** [UBC-MDS/cervical-cancer-predictor#34]
- [x] Please add instructions to create the conda environment. 
`conda env create -f`

- [x] The code structure from milestone 2 release (https://github.com/UBC-MDS/cervical-cancer-predictor/releases/tag/v0.1.0) doesn't match the instructions provided. Please fix these asap so I can run your code.

**Comment by samson-bakos** [comment]
Hi @muntakimrafi , apologies for the confusion but I think I know what's happening. We made a small error with the paths on our scripts that we are currently fixing for this week's release. If you navigate to the src subdirectory on terminal and run the commands from there it should run (I mentioned this briefly on the instructions but its obviously not standard practice so easy to miss). I just tested and the scripts run on my device when run from this directory.

It will be fixed to run from root by this weekend. Env create command is now on ReadMe

**Comment by muntakimrafi** [comment]
Please let me know after it is fixed. I will grade your assignments then.

**Comment by samson-bakos** [comment]
@muntakimrafi it should work now. There is a new release v0.1.1 that is the updated version.

**Comment by muntakimrafi** [comment]
Congratulations on finishing milestone 2!

- [x] Initially, the environment was set up incorrectly. -5
- [x] Analysis code is satisfactory.
- [x] Version controlling was satisfactory.
- [x]  I could run the code and reproduce the analysis. But I could not create the final report as the libraries required to create was not included in the environment file. -5
- [x] Submission expectations were met

**Comment by muntakimrafi** [comment]
The error I got while creating the final report

`Rscript -e "rmarkdown::render('Analysis_Docs/Analysis.Rmd')"
`

> processing file: Analysis.Rmd
  |......                                                                |   9%
  ordinary text without R code
  |.............                                                         |  18%
label: setup (with options) 
List of 1
 $ include: logi FALSE
Quitting from lines 10-12 (Analysis.Rmd) 
Error in library(tidyverse) : there is no package called 'tidyverse'
Calls: <Anonymous> ... withCallingHandlers -> withVisible -> eval -> eval -> library
Execution halted

**Comment by samson-bakos** [comment]
Thanks @muntakimrafi ! I spoke to another group that had a similar issue and Florencia suggested to them to add an additional step in the usage with a script to install r packages instead of including them in the .yaml, so I'm going to add that to ours as well
