### ISSUE TITLE
Milestone 4 to-do list

### ISSUE THREAD

**Issue by morrismanfung** [UBC-MDS/cervical-cancer-predictor#41]
## Summary
Edit by Samson, I'm taking over this thread

Work through this checklist as week goes on. If it is a quick fix (i.e. changing text in ReadMe), do it Main on Github. If its a larger fix make a branch.

If you are doing a task, flag it with your name (you can edit this comment as non author, I'm doing it right now) to prevent anyone else from working on the same thing. 

Main Tasks
- [x] Graph of Makefile -- @samson-bakos 
- [x] Docker -- @samson-bakos 
- [x] Address feedback (see Below)
- [x]  (ONCE DONE EVERYTHING) Re-run and push entire project (Use Docker) to make sure final results are correct

#### Feedback 
If you work on feedback, put your name on the list below to mark what you're doing to prevent conflicts. Once you do something, edit the comment at the bottom of this issue (https://github.com/UBC-MDS/data-analysis-review-2022/issues/10) with what you fixed, and a link to the commit where it was fixed. 

### Marked as Completed
- [x] Error messages in EDA's notebook. -- @WaielonH 
- [x] Changing the size of charts in EDA (?) -- @WaielonH
- [x] Remove models' `.joblib` in main, as they are now in `bin`? (I need some input from you, @WaielonH ) --@morrismanfung
- [x] Authors and date in codes.--@revathyponn
- [x] Authors and affiliation in report. --@revathyponn
- [x] Numeric prefixes for files. @morrismanfung 
- [x] Put scripts on separate lines in ReadMe Usage --Samson 
- [x] Add r installation commands to usage `Rscript -e "install.packages('tidyverse'), repos='https://cran.rstudio.com/')"`  --Samson 
- [x] Split large functions into smaller ones. -- Morris
- [x] Explain how the target variable is computed in the analysis report. @morrismanfung 
- [x] Explain how features are selected in the analysis report. @morrismanfung 
- [x] create a citation.cff file so people can cite our repo (add a note to readme that this repo is for learning purposes only and not actually a diagnostic tool) @morrismanfung 
- [x] add .md output to analysis, and set up GitHub pages for the .md @morrismanfung 
- [x] Round values in test-results.csv @morrismanfung 
- [x] References for python packages. -- @WaielonH 
- [x] Update Report to Mention Packaging via Make and Docker (Cite these as well ReadMe and .bib) -- @samson-bakos
- [x] Add context to false negatives vs false positives in analysis report -- why are we so concerned with recall? - @samson-bakos 
- [x] Add Make/ Docker Commands to ReadMe Usage  -- @samson-bakos will do after making Docker
