### ISSUE TITLE
Milestone 4 - Feedback

### ISSUE THREAD

**Issue by Glenn032787** [UBC-MDS/cervical-cancer-predictor#55]
**Congratulations on finishing milestone 4!** We can see you put a lot of work into this project, nice work!
Below we list some specific feedback you can use to improve your project.

## Dependency diagram of the Makefile (max 5 points)
Good Job

### Dockerfile
- [ ] The dependencie versions are not pinned. **-2 quality**
- [ ] Programming language and/or package versions are pinned using `>=` instead of `=`.
This means that each time the Docker image is built in the future,
the most recent version of the programming language and/or package will be installed in the container image.
This will lead to the container not being able to be reproducibly built in the future.  **-2 accuracy**
**Comment:** Missing dependency version for r-base and R packages. Used >= for scikit-learn and pandoc.

###  Analysis can be run reproducibly using documentation provided in the README
- [ ] Clearly specify usage instructions to the point a user could copy and paste them and they would work. 
If a specific value needs to be inserted (e.g., volume mounting, port forwarding, tag version - which should be specified, as relying on `latest` is unreliable for many reasons, etc) 
suggest the most reasonable value and provide the list 
(or link to a list) of alternative options. **-2 mechanics**
**Comment:** Did not include tag version when pulling docker container from dockerhub.

## Final Submission: Improve the project based on the feedback received
Good Job

### Expectations
- [ ] Please provide the link to the release as `https://github.com/UBC*MDS/REPOSITORY/tree/VERSION` 
(replacing `REPOSITORY` and `VERSION` with the correct ones for your project version for each milestone). 
This makes is a lot easier for someone to just visit the repository as it was at that point in the project's history. **-1 mechanics**
**Comment: Tag version submitted on canvas (v1.0.0) leads to an older version of github repo which does not include Makefile or Dockerfile. https://github.com/UBC-MDS/cervical-cancer-predictor/tree/v1.0.0 Used main branch to mark this milestone.**

**Comment by samson-bakos** [comment]
Hi @Glenn032787, thanks for the feedback! Regarding the release issues; this was due to a typo where our initial release was accidentally called 1.0.0 instead of 0.0.1 (I swear I read that in the milestone 1 instruction, maybe it was corrected and we missed it). I thought I renamed this tag to 0.0.1 in week 4 (which is how it appears in this list of releases https://github.com/UBC-MDS/cervical-cancer-predictor/releases) but you're right that the 1.0.0 link still returns to the week 1 version. Do you know how to permanently remove this footprint so 1.0.0 only links to latest?
